"""Initial migration.

Revision ID: 38524300bcd9
Revises: 
Create Date: 2024-07-29 22:56:35.371198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38524300bcd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_institution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('financial_institution_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['financial_institution_id'], ['financial_institution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    op.drop_table('financial_institution')
    # ### end Alembic commands ###
